In [1]:
import pandas as pd
import numpy as np
import timeit

file_path = 'data/household_power_consumption.txt'

def load_and_clean(path):
    df = pd.read_csv(path, sep=';', low_memory=False)
    
    df.replace('?', np.nan, inplace=True)
    df.dropna(inplace=True)
    
    numeric_cols = ['Global_active_power', 'Global_reactive_power', 'Voltage', 
                    'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3']
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col])
        
    df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S').dt.time
    return df

df = load_and_clean(file_path)
print(f"Завантажено записів: {len(df)}")
display(df.head())

Завантажено записів: 2049280

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0

In [3]:
def task_1(df):
    return df[df['Global_active_power'] > 5]

t1_time = timeit.timeit(lambda: task_1(df), number=1)
print(f"Час виконання: {t1_time:.5f} сек")
display(task_1(df).head())

Час виконання: 0.00944 сек

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
11,16/12/2006,17:35:00,5.412,0.470,232.78,23.2,0.0,1.0,17.0
12,16/12/2006,17:36:00,5.224,0.478,232.99,22.4,0.0,1.0,16.0

In [5]:
def task_2(df):
    return df[(df['Global_intensity'] >= 19) & 
              (df['Global_intensity'] <= 20) & 
              (df['Sub_metering_2'] > df['Sub_metering_3'])]

t2_time = timeit.timeit(lambda: task_2(df), number=1)
print(f"Час виконання: {t2_time:.5f} сек")
display(task_2(df).head())

Час виконання: 0.02366 сек

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
45,16/12/2006,18:09:00,4.464,0.136,234.66,19.0,0.0,37.0,16.0
460,17/12/2006,01:04:00,4.582,0.258,238.08,19.6,0.0,13.0,0.0
464,17/12/2006,01:08:00,4.618,0.104,239.61,19.6,0.0,27.0,0.0
475,17/12/2006,01:19:00,4.636,0.140,237.37,19.4,0.0,36.0,0.0
476,17/12/2006,01:20:00,4.634,0.152,237.17,19.4,0.0,35.0,0.0

In [6]:
def task_3(df):
    sample = df.sample(n=500000, replace=False) 
    return sample[['Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3']].mean()

t3_time = timeit.timeit(lambda: task_3(df), number=1)
print(f"Час виконання: {t3_time:.5f} сек")
print("Середні значення груп споживання:")
print(task_3(df))

Час виконання: 0.85612 сек
Середні значення груп споживання:
Sub_metering_1    1.122446
Sub_metering_2    1.292454
Sub_metering_3    6.461860
dtype: float64

In [7]:
import datetime

def task_4(df):
    time_limit = datetime.time(18, 0, 0)
    subset = df[(df['Time'] > time_limit) & (df['Global_active_power'] > 6)]
     
    subset = subset[(subset['Sub_metering_2'] > subset['Sub_metering_1']) & 
                    (subset['Sub_metering_2'] > subset['Sub_metering_3'])]
     
    half = len(subset) // 2
    first_half = subset.iloc[:half:3] 
    second_half = subset.iloc[half::4]
    
    return pd.concat([first_half, second_half])

t4_time = timeit.timeit(lambda: task_4(df), number=1)
print(f"Час виконання: {t4_time:.5f} сек")
display(task_4(df).head())

Час виконання: 0.19603 сек

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
41,16/12/2006,18:05:00,6.052,0.192,232.93,26.2,0.0,37.0,17.0
44,16/12/2006,18:08:00,6.308,0.116,232.25,27.0,0.0,36.0,17.0
17494,28/12/2006,20:58:00,6.386,0.374,236.63,27.0,1.0,36.0,17.0
17498,28/12/2006,21:02:00,8.088,0.262,235.50,34.4,1.0,72.0,17.0
17501,28/12/2006,21:05:00,7.230,0.152,235.22,30.6,1.0,73.0,17.0